version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "transfer_api_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./database:/data/db
    ports:
      - 27019:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet