version: '3'
services:
  web:
    build: .
    container_name: "transfer_api"
    environment:
      MONGO_URL: 'mongodb://mongodb:27017'
    ports:
      - "8080:8080"
      - "56745:56745"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "transfer_api_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
